<a href="https://colab.research.google.com/github/minzee09/food-nutrition-image-recognizer/blob/main/food_nutrition_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import tensorflow_datasets as tfds

import numpy as np
#오류 해결용
tf.config.run_functions_eagerly(True)

The split parameter can be set to 'train' or 'test' to load the training or test split of the dataset, respectively.<br>
The as_supervised parameter ensures that the dataset is returned as a tuple of (image, label) pairs.

In [ ]:
# food101(음식 이미지) 데이터셋
food101_dataset = tfds.load('food101', split='train', as_supervised=True)

In [ ]:
food101_dataset, info = tfds.load('food101', split='train', with_info=True)

In [ ]:
# #food101 데이터셋 카테고리 출력
categories = info.features['label'].names
print("Categories in Food101 dataset:", categories)

Categories in Food101 dataset: ['apple_pie', 'baby_back_ribs', 'baklava', 'beef_carpaccio', 'beef_tartare', 'beet_salad', 'beignets', 'bibimbap', 'bread_pudding', 'breakfast_burrito', 'bruschetta', 'caesar_salad', 'cannoli', 'caprese_salad', 'carrot_cake', 'ceviche', 'cheesecake', 'cheese_plate', 'chicken_curry', 'chicken_quesadilla', 'chicken_wings', 'chocolate_cake', 'chocolate_mousse', 'churros', 'clam_chowder', 'club_sandwich', 'crab_cakes', 'creme_brulee', 'croque_madame', 'cup_cakes', 'deviled_eggs', 'donuts', 'dumplings', 'edamame', 'eggs_benedict', 'escargots', 'falafel', 'filet_mignon', 'fish_and_chips', 'foie_gras', 'french_fries', 'french_onion_soup', 'french_toast', 'fried_calamari', 'fried_rice', 'frozen_yogurt', 'garlic_bread', 'gnocchi', 'greek_salad', 'grilled_cheese_sandwich', 'grilled_salmon', 'guacamole', 'gyoza', 'hamburger', 'hot_and_sour_soup', 'hot_dog', 'huevos_rancheros', 'hummus', 'ice_cream', 'lasagna', 'lobster_bisque', 'lobster_roll_sandwich', 'macaroni_and

In [ ]:
# 데이터 전처리 함수 정의
def preprocess_image_with_nutrition(image, label):
    print("Image shape:", image.shape)
    print("Label:", label)
    # Resize
    image = tf.image.resize(image, [224, 224])
    image = tf.cast(image, tf.float32) / 255.0

   #라벨 텐서 -> 파이썬 문자열 변환
    label_str = tf.strings.as_string(label)
    label_str_np = label_str.numpy().decode('utf-8')
    nutritional_info = nutrition_mapping.get(label_str_np, {'sugar': 0, 'carbs': 0, 'protein': 0, 'fat': 0})

    sugar = tf.constant(nutritional_info['sugar'], dtype=tf.float32)
    carbs = tf.constant(nutritional_info['carbs'], dtype=tf.float32)
    protein = tf.constant(nutritional_info['protein'], dtype=tf.float32)
    fat = tf.constant(nutritional_info['fat'], dtype=tf.float32)

    nutrition_tensor = tf.stack([sugar, carbs, protein, fat])

    return image, nutrition_tensor


In [ ]:
# 이미지와 영양성분 매핑
nutrition_mapping = {
    'bibimbap': {'sugar': 18.3, 'carbs': 98.7, 'protein': 24.6, 'fat': 22},
    'apple_pie': {'sugar': 9, 'carbs': 3, 'protein': 0, 'fat': 0},
    # 더 추가 예정
}

In [ ]:
batch_size=32
#오류 해결해야 함
#batched_dataset_with_nutrition = food101_dataset.map(preprocess_image_with_nutrition).batch(batch_size)

In [ ]:
# Iterate through the batched dataset
for batch_images, batch_labels in batched_dataset_with_nutrition:
    # Process each batch here (e.g., label, train model, etc.)
    print(batch_images.shape, batch_labels)


스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
 28 48 62 48 84 46 38  9], shape=(32,), dtype=int64)
(32, 224, 224, 3) tf.Tensor(
[52 45 39 27  9 18 78 97 70 77 48 58  9  1 27 60 45 12 58 22  5 82  4 66
 40 87 56 19 58 70 30 14], shape=(32,), dtype=int64)
(32, 224, 224, 3) tf.Tensor(
[79 32 41 71 42 14 39 14 94 30 62 99 37 42 36 96 44 47 92 73 81 96 15 79
 77  0 64 53 45 76 25 21], shape=(32,), dtype=int64)
(32, 224, 224, 3) tf.Tensor(
[55 50  0 89  9 47 35 64 61 64 56 92 98 40 13 52 56 45 28 87 57  1 12 50
 46 78 36 80 97 79 47 98], shape=(32,), dtype=int64)
(32, 224, 224, 3) tf.Tensor(
[90  1  6 87 86 86 26 92 19 11 45 90 43 81 98 45 73 82 98 18 22 42 29 57
 76 70 47 83 95 51 94 46], shape=(32,), dtype=int64)
(32, 224, 224, 3) tf.Tensor(
[39 55  2 30  9 61 56 17 53 23 38 21 60 22 26 18 61 20 85 52 71 41 35 28
 54 22 85 95 84 28 96 78], shape=(32,), dtype=int64)
(32, 224, 224, 3) tf.Tensor(
[73 75 62 46 28 27 46 12 21 94 52 47 64 96 14 45 94 93 76  9 56 50 49 81
  7 50 60  9 14 26 94 36], shape=(